export const APC_MINI_MK2_HARDWARE_CONFIG = {
  FADER_COUNT: 9,
  FADER_BUTTON_COUNT: 9,
  PAGE_BUTTON_COUNT: 8,
  GRID_SIZE: 8,
} as const;

export const APC_MINI_MK2_NOTE_RANGES = {
  GRID: { START: 0, END: 63 },
  FADER_BUTTONS: { START: 100, END: 107 },
  SIDE_BUTTONS: { START: 112, END: 119 },
  FADERS: { START: 48, END: 56 },
  SHIFT_BUTTON: 122,
} as const;

export const APC_MINI_MK2_GRID_LED_NOTE_ON_STATUS = 0x96;
